# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q9pooYplFopdhR0XIrQhseleSPSx5idF
"""

import numpy as np
import pandas
from flask import Flask, request, jsonify, render_template
import pickle
import inputscript

app = Flask(__name__)
model = pickle.load(open('Phishing_Website.pkl','rb'))


@app.route("/")
def predict():
    return render_template('index.html')

ans = ""   
bns = ""   
@app.route('/result_processing_function', methods=['POST','GET'])
def y_predict():
    url = request.form['url']
    checkprediction = inputscript.main(url)
    prediction = model.predict(checkprediction)
    print(prediction)
    output=prediction[0]
    if(output==1):
        pred="You are safe!!  This is a legitimate Website."
        return render_template('index.html',bns=pred)
    
    else:
        pred="You are on the wrong site. Be cautious!"        
        return render_template('index.html',ans=pred)


@app.route('/predict_api', methods=['POST'])
def predict_api():
    
    data = request.get_json(force=True)
    prediction = model.y_predict([np.array(list(data.values()))])

    output=prediction[0]
    return jsonify(output)        
 
if __name__ == '__main__':
    app.run(host = '127.0.0.1')